import {
  STRUCTURE_RELATIONSHIP_KINDS,
  STRUCTURE_SECTION_KEYS,
} from "../../../catalogue/structure-vocabulary.ts";
import {
  ACADEMIC_STRUCTURE_EXTRACTION_SCHEMA_VERSION,
  ACADEMIC_STRUCTURE_KINDS,
} from "./contract.ts";

const nullableNumberSchema = { type: ["number", "null"], minimum: 0 };
const nullableStringSchema = { type: ["string", "null"] };

// OpenRouter receives this schema alongside the trusted prompt. Runtime
// validation in contract.ts remains authoritative for cross-field and selected-target
// checks that JSON Schema cannot express clearly.
export const ACADEMIC_STRUCTURE_EXTRACTION_JSON_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "schemaVersion",
    "kind",
    "code",
    "year",
    "title",
    "acronym",
    "shortName",
    "introduction",
    "description",
    "totalUnits",
    "durationYears",
    "academicCareer",
    "college",
    "deliveryMode",
    "selectionRank",
    "atar",
    "canCombine",
    "canCombineVertical",
    "studyAs",
    "contactText",
    "summaryFields",
    "sections",
    "learningOutcomes",
    "fees",
    "relationships",
    "requirements",
    "evidence",
    "overallConfidence",
    "reviewItems",
  ],
  properties: {
    schemaVersion: { const: ACADEMIC_STRUCTURE_EXTRACTION_SCHEMA_VERSION },
    kind: { enum: ACADEMIC_STRUCTURE_KINDS },
    code: { type: "string", pattern: "^[A-Z0-9][A-Z0-9-]{1,31}$" },
    year: { type: "integer", minimum: 2020, maximum: 2030 },
    title: { type: "string", minLength: 1 },
    acronym: nullableStringSchema,
    shortName: nullableStringSchema,
    introduction: nullableStringSchema,
    description: nullableStringSchema,
    totalUnits: nullableNumberSchema,
    durationYears: {
      type: ["number", "null"],
      exclusiveMinimum: 0,
    },
    academicCareer: nullableStringSchema,
    college: nullableStringSchema,
    deliveryMode: nullableStringSchema,
    selectionRank: nullableNumberSchema,
    atar: nullableNumberSchema,
    canCombine: { type: ["boolean", "null"] },
    canCombineVertical: { type: ["boolean", "null"] },
    studyAs: nullableStringSchema,
    contactText: nullableStringSchema,
    summaryFields: {
      type: "array",
      items: { $ref: "#/$defs/summaryField" },
    },
    sections: { type: "array", items: { $ref: "#/$defs/section" } },
    learningOutcomes: {
      type: "array",
      items: { $ref: "#/$defs/learningOutcome" },
    },
    fees: { type: "array", items: { $ref: "#/$defs/fee" } },
    relationships: {
      type: "array",
      items: { $ref: "#/$defs/relationship" },
    },
    requirements: { $ref: "#/$defs/requirements" },
    evidence: { type: "array", items: { $ref: "#/$defs/evidence" } },
    overallConfidence: {
      type: ["number", "null"],
      minimum: 0,
      maximum: 1,
    },
    reviewItems: {
      type: "array",
      items: { $ref: "#/$defs/reviewItem" },
    },
  },
  $defs: {
    nullableString: nullableStringSchema,
    summaryField: {
      type: "object",
      additionalProperties: false,
      required: ["position", "key", "label", "values", "sourceText"],
      properties: {
        position: { type: "integer", minimum: 1 },
        key: {
          type: "string",
          pattern: "^[a-z0-9]+(?:_[a-z0-9]+)*$",
        },
        label: { type: "string", minLength: 1 },
        values: {
          type: "array",
          minItems: 1,
          items: { type: "string", minLength: 1 },
        },
        sourceText: { type: "string", minLength: 1 },
      },
    },
    section: {
      type: "object",
      additionalProperties: false,
      required: ["key", "markdown", "sourceText", "sourceLocator"],
      properties: {
        key: { enum: [...STRUCTURE_SECTION_KEYS] },
        markdown: { type: "string", minLength: 1 },
        sourceText: { type: "string", minLength: 1 },
        sourceLocator: { type: "string", minLength: 1 },
      },
    },
    learningOutcome: {
      type: "object",
      additionalProperties: false,
      required: ["position", "text", "sourceText", "sourceLocator"],
      properties: {
        position: { type: "integer", minimum: 1 },
        text: { type: "string", minLength: 1 },
        sourceText: { type: "string", minLength: 1 },
        sourceLocator: { type: "string", minLength: 1 },
      },
    },
    fee: {
      type: "object",
      additionalProperties: false,
      required: [
        "position",
        "feeYear",
        "audience",
        "feeType",
        "amount",
        "currency",
        "basis",
        "sourceLabel",
        "sourceText",
        "sourceLocator",
      ],
      properties: {
        position: { type: "integer", minimum: 1 },
        feeYear: { type: ["integer", "null"], minimum: 2000, maximum: 2200 },
        audience: {
          enum: [
            "domestic",
            "international",
            "commonwealth_supported",
            "other",
          ],
        },
        feeType: {
          enum: ["student_contribution", "tuition", "indicative", "other"],
        },
        amount: nullableNumberSchema,
        currency: { enum: ["AUD", null] },
        basis: {
          enum: ["programme", "unit", "eftsl", "annual", "unknown"],
        },
        sourceLabel: nullableStringSchema,
        sourceText: { type: "string", minLength: 1 },
        sourceLocator: { type: "string", minLength: 1 },
      },
    },
    relationship: {
      type: "object",
      additionalProperties: false,
      required: [
        "position",
        "relationshipKind",
        "targetKind",
        "targetCode",
        "targetTitle",
        "sourceText",
        "sourceLocator",
      ],
      properties: {
        position: { type: "integer", minimum: 1 },
        relationshipKind: { enum: [...STRUCTURE_RELATIONSHIP_KINDS] },
        targetKind: { enum: [...ACADEMIC_STRUCTURE_KINDS] },
        targetCode: { type: "string", minLength: 1 },
        targetTitle: nullableStringSchema,
        sourceText: { type: "string", minLength: 1 },
        sourceLocator: { type: "string", minLength: 1 },
      },
    },
    requirementRule: {
      oneOf: [
        { $ref: "#/$defs/requirementGroup" },
        { $ref: "#/$defs/requirementCondition" },
      ],
    },
    requirementGroup: {
      type: "object",
      additionalProperties: false,
      required: [
        "type",
        "key",
        "operator",
        "minimumCount",
        "scope",
        "title",
        "sourceText",
        "sourceLocator",
        "children",
      ],
      properties: {
        type: { const: "group" },
        key: { type: "string", minLength: 1 },
        operator: { enum: ["all_of", "any_of", "minimum_count"] },
        minimumCount: { type: ["integer", "null"], minimum: 1 },
        scope: { enum: ["part", "degree"] },
        title: nullableStringSchema,
        sourceText: { type: "string", minLength: 1 },
        sourceLocator: { type: "string", minLength: 1 },
        children: {
          type: "array",
          minItems: 1,
          items: { $ref: "#/$defs/requirementRule" },
        },
      },
    },
    requirementCondition: {
      type: "object",
      additionalProperties: false,
      required: [
        "type",
        "key",
        "conditionKind",
        "minimumUnits",
        "maximumUnits",
        "minimumCourses",
        "courseCodes",
        "structureKind",
        "structureCodes",
        "subjectCode",
        "minimumLevel",
        "maximumLevel",
        "tag",
        "freeText",
        "scope",
        "includesAnyCourse",
        "sourceText",
        "sourceLocator",
      ],
      properties: {
        type: { const: "condition" },
        key: { type: "string", minLength: 1 },
        conditionKind: {
          enum: [
            "course_list",
            "consecutive_semester_pair",
            "structure_list",
            "unit_total",
            "level",
            "subject",
            "tag",
            "unrestricted",
            "free_text",
          ],
        },
        minimumUnits: nullableNumberSchema,
        maximumUnits: nullableNumberSchema,
        minimumCourses: { type: ["integer", "null"], minimum: 1 },
        courseCodes: {
          type: "array",
          uniqueItems: true,
          items: {
            type: "string",
            pattern: "^[A-Z]{4}[0-9]{4}[A-Z]?$",
          },
        },
        structureKind: { enum: [...ACADEMIC_STRUCTURE_KINDS, null] },
        structureCodes: {
          type: "array",
          uniqueItems: true,
          items: {
            type: "string",
            pattern: "^[A-Z0-9][A-Z0-9-]{1,31}$",
          },
        },
        subjectCode: {
          type: ["string", "null"],
          pattern: "^[A-Z]{4}$",
        },
        minimumLevel: { type: ["integer", "null"], minimum: 0 },
        maximumLevel: { type: ["integer", "null"], minimum: 0 },
        tag: nullableStringSchema,
        freeText: nullableStringSchema,
        scope: { enum: ["part", "degree"] },
        includesAnyCourse: { type: "boolean" },
        sourceText: { type: "string", minLength: 1 },
        sourceLocator: { type: "string", minLength: 1 },
      },
    },
    requirements: {
      type: "object",
      additionalProperties: false,
      required: ["sourceText", "sourceLocator", "rule", "unmodelledText"],
      properties: {
        sourceText: nullableStringSchema,
        sourceLocator: nullableStringSchema,
        rule: {
          anyOf: [{ $ref: "#/$defs/requirementRule" }, { type: "null" }],
        },
        unmodelledText: {
          type: "array",
          items: { type: "string", minLength: 1 },
        },
      },
    },
    evidence: {
      type: "object",
      additionalProperties: false,
      required: [
        "fieldKey",
        "sourceLocator",
        "evidenceExcerpt",
        "confidence",
        "method",
      ],
      properties: {
        fieldKey: { type: "string", minLength: 1 },
        sourceLocator: { type: "string", minLength: 1 },
        evidenceExcerpt: { type: "string", minLength: 1 },
        confidence: { type: "number", minimum: 0, maximum: 1 },
        method: { const: "model" },
      },
    },
    reviewItem: {
      type: "object",
      additionalProperties: false,
      required: ["fieldKey", "kind", "severity", "message"],
      properties: {
        fieldKey: { type: "string", minLength: 1 },
        kind: {
          enum: [
            "missing",
            "ambiguous",
            "conflict",
            "unsupported",
            "invalid",
            "evidence_missing",
          ],
        },
        severity: { enum: ["warning", "error"] },
        message: { type: "string", minLength: 1 },
      },
    },
  },
} as const;
