import type { ShowcaseCourse } from "@/lib/coursemap/landing-courses";

/**
 * Four real courses from the published 2026 catalogue whose prerequisites
 * take three or more courses to meet, snapshotted so the landing and
 * sign-in pages show them instantly without querying the catalogue. Only
 * the course links the views draw are kept. Refresh by hand
 * if these courses' rules change.
 */
export const SHOWCASE_COURSES: readonly ShowcaseCourse[] = [
  {
    code: "FINM3045",
    name: "Asian Capital Markets",
    year: 2026,
    enrolmentRule: {
      kind: "group",
      operator: "all_of",
      minimumCount: null,
      conditions: [
        {
          kind: "group",
          operator: "all_of",
          minimumCount: null,
          conditions: [
            {
              confidence: 1,
              hardness: "hard",
              reviewState: "automatic",
              sourceText: "Completed FINM1001",
              kind: "course",
              code: "FINM1001",
              minimumMark: null,
              requirementMode: "completed",
            },
            {
              confidence: 1,
              hardness: "hard",
              reviewState: "automatic",
              sourceText: "Completed FINM2001",
              kind: "course",
              code: "FINM2001",
              minimumMark: null,
              requirementMode: "completed",
            },
            {
              confidence: 1,
              hardness: "hard",
              reviewState: "automatic",
              sourceText: "Completed FINM2002",
              kind: "course",
              code: "FINM2002",
              minimumMark: null,
              requirementMode: "completed",
            },
            {
              kind: "group",
              operator: "any_of",
              minimumCount: null,
              conditions: [
                {
                  confidence: 1,
                  hardness: "hard",
                  reviewState: "automatic",
                  sourceText: "Completed FINM2003",
                  kind: "course",
                  code: "FINM2003",
                  minimumMark: null,
                  requirementMode: "completed",
                },
                {
                  confidence: 1,
                  hardness: "hard",
                  reviewState: "automatic",
                  sourceText: "Completed FINM3011",
                  kind: "course",
                  code: "FINM3011",
                  minimumMark: null,
                  requirementMode: "completed",
                },
              ],
            },
          ],
        },
        {
          kind: "group",
          operator: "all_of",
          minimumCount: null,
          conditions: [
            {
              confidence: 1,
              hardness: "hard",
              reviewState: "verified",
              sourceText: "Incompatible with FINM6045.",
              kind: "incompatible",
              code: "FINM6045",
            },
            {
              confidence: 1,
              hardness: "hard",
              reviewState: "verified",
              sourceText: "",
              kind: "incompatible_concurrent",
              code: "FINM6045",
            },
          ],
        },
      ],
    },
    prerequisiteRule: {
      kind: "group",
      operator: "all_of",
      minimumCount: null,
      conditions: [
        {
          confidence: 1,
          hardness: "hard",
          reviewState: "automatic",
          sourceText: "Completed FINM1001",
          kind: "course",
          code: "FINM1001",
          minimumMark: null,
          requirementMode: "completed",
        },
        {
          confidence: 1,
          hardness: "hard",
          reviewState: "automatic",
          sourceText: "Completed FINM2001",
          kind: "course",
          code: "FINM2001",
          minimumMark: null,
          requirementMode: "completed",
        },
        {
          confidence: 1,
          hardness: "hard",
          reviewState: "automatic",
          sourceText: "Completed FINM2002",
          kind: "course",
          code: "FINM2002",
          minimumMark: null,
          requirementMode: "completed",
        },
        {
          kind: "group",
          operator: "any_of",
          minimumCount: null,
          conditions: [
            {
              confidence: 1,
              hardness: "hard",
              reviewState: "automatic",
              sourceText: "Completed FINM2003",
              kind: "course",
              code: "FINM2003",
              minimumMark: null,
              requirementMode: "completed",
            },
            {
              confidence: 1,
              hardness: "hard",
              reviewState: "automatic",
              sourceText: "Completed FINM3011",
              kind: "course",
              code: "FINM3011",
              minimumMark: null,
              requirementMode: "completed",
            },
          ],
        },
      ],
    },
    hasPrerequisiteWording: true,
    availableCourseCodes: ["FINM1001", "FINM2001", "FINM2002", "FINM3011"],
  },
  {
    code: "ECON2125",
    name: "Optimisation for Economics and Financial Economics",
    year: 2026,
    enrolmentRule: {
      kind: "group",
      operator: "all_of",
      minimumCount: null,
      conditions: [
        {
          kind: "group",
          operator: "all_of",
          minimumCount: null,
          conditions: [
            {
              kind: "group",
              operator: "all_of",
              minimumCount: null,
              conditions: [
                {
                  confidence: 1,
                  hardness: "hard",
                  reviewState: "verified",
                  sourceText: "Completed ECON1100",
                  kind: "course",
                  code: "ECON1101",
                  minimumMark: null,
                  requirementMode: "completed",
                },
                {
                  kind: "group",
                  operator: "any_of",
                  minimumCount: null,
                  conditions: [
                    {
                      confidence: 1,
                      hardness: "hard",
                      reviewState: "verified",
                      sourceText: "Completed ECON1101",
                      kind: "course",
                      code: "ECON1100",
                      minimumMark: null,
                      requirementMode: "completed",
                    },
                    {
                      confidence: 1,
                      hardness: "hard",
                      reviewState: "verified",
                      sourceText: "Completed ECON1102",
                      kind: "course",
                      code: "ECON1102",
                      minimumMark: null,
                      requirementMode: "completed",
                    },
                  ],
                },
              ],
            },
            {
              kind: "group",
              operator: "any_of",
              minimumCount: null,
              conditions: [
                {
                  confidence: 1,
                  hardness: "hard",
                  reviewState: "verified",
                  sourceText: "Completed EMET1001",
                  kind: "course",
                  code: "EMET1001",
                  minimumMark: null,
                  requirementMode: "completed",
                },
                {
                  confidence: 1,
                  hardness: "hard",
                  reviewState: "verified",
                  sourceText: "Completed MATH1014",
                  kind: "course",
                  code: "MATH1014",
                  minimumMark: null,
                  requirementMode: "completed",
                },
                {
                  confidence: 1,
                  hardness: "hard",
                  reviewState: "verified",
                  sourceText: "Completed MATH1113",
                  kind: "course",
                  code: "MATH1113",
                  minimumMark: null,
                  requirementMode: "completed",
                },
                {
                  confidence: 1,
                  hardness: "hard",
                  reviewState: "verified",
                  sourceText: "Completed MATH1116",
                  kind: "course",
                  code: "MATH1116",
                  minimumMark: null,
                  requirementMode: "completed",
                },
              ],
            },
          ],
        },
        {
          kind: "group",
          operator: "all_of",
          minimumCount: null,
          conditions: [
            {
              confidence: 1,
              hardness: "hard",
              reviewState: "automatic",
              sourceText: "Incompatible with ECON6012 and ECON8013.",
              kind: "incompatible",
              code: "ECON6012",
            },
            {
              confidence: 1,
              hardness: "hard",
              reviewState: "automatic",
              sourceText: "Incompatible with ECON6012 and ECON8013.",
              kind: "incompatible",
              code: "ECON8013",
            },
            {
              confidence: 1,
              hardness: "hard",
              reviewState: "automatic",
              sourceText: "Incompatible with ECON6012 and ECON8013.",
              kind: "incompatible_concurrent",
              code: "ECON6012",
            },
            {
              confidence: 1,
              hardness: "hard",
              reviewState: "automatic",
              sourceText: "Incompatible with ECON6012 and ECON8013.",
              kind: "incompatible_concurrent",
              code: "ECON8013",
            },
          ],
        },
      ],
    },
    prerequisiteRule: {
      kind: "group",
      operator: "all_of",
      minimumCount: null,
      conditions: [
        {
          kind: "group",
          operator: "all_of",
          minimumCount: null,
          conditions: [
            {
              confidence: 1,
              hardness: "hard",
              reviewState: "verified",
              sourceText: "Completed ECON1100",
              kind: "course",
              code: "ECON1101",
              minimumMark: null,
              requirementMode: "completed",
            },
            {
              kind: "group",
              operator: "any_of",
              minimumCount: null,
              conditions: [
                {
                  confidence: 1,
                  hardness: "hard",
                  reviewState: "verified",
                  sourceText: "Completed ECON1101",
                  kind: "course",
                  code: "ECON1100",
                  minimumMark: null,
                  requirementMode: "completed",
                },
                {
                  confidence: 1,
                  hardness: "hard",
                  reviewState: "verified",
                  sourceText: "Completed ECON1102",
                  kind: "course",
                  code: "ECON1102",
                  minimumMark: null,
                  requirementMode: "completed",
                },
              ],
            },
          ],
        },
        {
          kind: "group",
          operator: "any_of",
          minimumCount: null,
          conditions: [
            {
              confidence: 1,
              hardness: "hard",
              reviewState: "verified",
              sourceText: "Completed EMET1001",
              kind: "course",
              code: "EMET1001",
              minimumMark: null,
              requirementMode: "completed",
            },
            {
              confidence: 1,
              hardness: "hard",
              reviewState: "verified",
              sourceText: "Completed MATH1014",
              kind: "course",
              code: "MATH1014",
              minimumMark: null,
              requirementMode: "completed",
            },
            {
              confidence: 1,
              hardness: "hard",
              reviewState: "verified",
              sourceText: "Completed MATH1113",
              kind: "course",
              code: "MATH1113",
              minimumMark: null,
              requirementMode: "completed",
            },
            {
              confidence: 1,
              hardness: "hard",
              reviewState: "verified",
              sourceText: "Completed MATH1116",
              kind: "course",
              code: "MATH1116",
              minimumMark: null,
              requirementMode: "completed",
            },
          ],
        },
      ],
    },
    hasPrerequisiteWording: true,
    availableCourseCodes: [
      "ECON1100",
      "ECON1101",
      "ECON1102",
      "EMET1001",
      "MATH1014",
      "MATH1113",
      "MATH1116",
    ],
  },
  {
    code: "PSYC3026",
    name: "Personality Psychology",
    year: 2026,
    enrolmentRule: {
      kind: "group",
      operator: "all_of",
      minimumCount: null,
      conditions: [
        {
          kind: "group",
          operator: "all_of",
          minimumCount: null,
          conditions: [
            {
              confidence: 0,
              hardness: "hard",
              reviewState: "automatic",
              sourceText: "Completed PSYC1003",
              kind: "course",
              code: "PSYC1003",
              minimumMark: null,
              requirementMode: "completed",
            },
            {
              confidence: 0,
              hardness: "hard",
              reviewState: "automatic",
              sourceText: "Completed PSYC1004",
              kind: "course",
              code: "PSYC1004",
              minimumMark: null,
              requirementMode: "completed",
            },
            {
              confidence: 0,
              hardness: "hard",
              reviewState: "automatic",
              sourceText: "Completed PSYC2009",
              kind: "course",
              code: "PSYC2009",
              minimumMark: null,
              requirementMode: "completed",
            },
          ],
        },
        {
          kind: "group",
          operator: "all_of",
          minimumCount: null,
          conditions: [
            {
              confidence: 0,
              hardness: "hard",
              reviewState: "automatic",
              sourceText:
                "You are not able to enrol in this course if you have previously completed PSYC3021, PSYC3001 or PSYC2004.",
              kind: "incompatible",
              code: "PSYC2004",
            },
            {
              confidence: 0,
              hardness: "hard",
              reviewState: "automatic",
              sourceText:
                "You are not able to enrol in this course if you have previously completed PSYC3021, PSYC3001 or PSYC2004.",
              kind: "incompatible",
              code: "PSYC3001",
            },
            {
              confidence: 0,
              hardness: "hard",
              reviewState: "automatic",
              sourceText:
                "You are not able to enrol in this course if you have previously completed PSYC3021, PSYC3001 or PSYC2004.",
              kind: "incompatible",
              code: "PSYC3021",
            },
          ],
        },
      ],
    },
    prerequisiteRule: {
      kind: "group",
      operator: "all_of",
      minimumCount: null,
      conditions: [
        {
          confidence: 0,
          hardness: "hard",
          reviewState: "automatic",
          sourceText: "Completed PSYC1003",
          kind: "course",
          code: "PSYC1003",
          minimumMark: null,
          requirementMode: "completed",
        },
        {
          confidence: 0,
          hardness: "hard",
          reviewState: "automatic",
          sourceText: "Completed PSYC1004",
          kind: "course",
          code: "PSYC1004",
          minimumMark: null,
          requirementMode: "completed",
        },
        {
          confidence: 0,
          hardness: "hard",
          reviewState: "automatic",
          sourceText: "Completed PSYC2009",
          kind: "course",
          code: "PSYC2009",
          minimumMark: null,
          requirementMode: "completed",
        },
      ],
    },
    hasPrerequisiteWording: true,
    availableCourseCodes: [],
  },
  {
    code: "STAT3017",
    name: "Big Data Statistics",
    year: 2026,
    enrolmentRule: {
      kind: "group",
      operator: "all_of",
      minimumCount: null,
      conditions: [
        {
          kind: "group",
          operator: "all_of",
          minimumCount: null,
          conditions: [
            {
              kind: "group",
              operator: "any_of",
              minimumCount: null,
              conditions: [
                {
                  confidence: 0,
                  hardness: "hard",
                  reviewState: "automatic",
                  sourceText: "Completed STAT2001",
                  kind: "course",
                  code: "STAT2001",
                  minimumMark: null,
                  requirementMode: "completed",
                },
                {
                  confidence: 0,
                  hardness: "hard",
                  reviewState: "automatic",
                  sourceText: "Completed STAT2013",
                  kind: "course",
                  code: "STAT2013",
                  minimumMark: null,
                  requirementMode: "completed",
                },
              ],
            },
            {
              kind: "group",
              operator: "any_of",
              minimumCount: null,
              conditions: [
                {
                  confidence: 0,
                  hardness: "hard",
                  reviewState: "automatic",
                  sourceText: "Completed STAT2008",
                  kind: "course",
                  code: "STAT2008",
                  minimumMark: null,
                  requirementMode: "completed",
                },
                {
                  confidence: 0,
                  hardness: "hard",
                  reviewState: "automatic",
                  sourceText: "Completed STAT2014",
                  kind: "course",
                  code: "STAT2014",
                  minimumMark: null,
                  requirementMode: "completed",
                },
                {
                  confidence: 0,
                  hardness: "hard",
                  reviewState: "automatic",
                  sourceText: "Completed STAT3008",
                  kind: "course",
                  code: "STAT3008",
                  minimumMark: null,
                  requirementMode: "completed",
                },
              ],
            },
            {
              kind: "group",
              operator: "any_of",
              minimumCount: null,
              conditions: [
                {
                  confidence: 0,
                  hardness: "hard",
                  reviewState: "automatic",
                  sourceText: "Completed MATH1113",
                  kind: "course",
                  code: "MATH1113",
                  minimumMark: null,
                  requirementMode: "completed",
                },
                {
                  confidence: 0,
                  hardness: "hard",
                  reviewState: "automatic",
                  sourceText: "Completed MATH1014",
                  kind: "course",
                  code: "MATH1014",
                  minimumMark: null,
                  requirementMode: "completed",
                },
                {
                  confidence: 0,
                  hardness: "hard",
                  reviewState: "automatic",
                  sourceText: "Completed MATH1116",
                  kind: "course",
                  code: "MATH1116",
                  minimumMark: null,
                  requirementMode: "completed",
                },
              ],
            },
          ],
        },
        {
          kind: "group",
          operator: "all_of",
          minimumCount: null,
          conditions: [
            {
              confidence: 0,
              hardness: "hard",
              reviewState: "automatic",
              sourceText: "Incompatible with STAT6017.",
              kind: "incompatible",
              code: "STAT6017",
            },
            {
              confidence: 0,
              hardness: "hard",
              reviewState: "automatic",
              sourceText: "Incompatible with STAT6017.",
              kind: "incompatible_concurrent",
              code: "STAT6017",
            },
          ],
        },
      ],
    },
    prerequisiteRule: {
      kind: "group",
      operator: "all_of",
      minimumCount: null,
      conditions: [
        {
          kind: "group",
          operator: "any_of",
          minimumCount: null,
          conditions: [
            {
              confidence: 0,
              hardness: "hard",
              reviewState: "automatic",
              sourceText: "Completed STAT2001",
              kind: "course",
              code: "STAT2001",
              minimumMark: null,
              requirementMode: "completed",
            },
            {
              confidence: 0,
              hardness: "hard",
              reviewState: "automatic",
              sourceText: "Completed STAT2013",
              kind: "course",
              code: "STAT2013",
              minimumMark: null,
              requirementMode: "completed",
            },
          ],
        },
        {
          kind: "group",
          operator: "any_of",
          minimumCount: null,
          conditions: [
            {
              confidence: 0,
              hardness: "hard",
              reviewState: "automatic",
              sourceText: "Completed STAT2008",
              kind: "course",
              code: "STAT2008",
              minimumMark: null,
              requirementMode: "completed",
            },
            {
              confidence: 0,
              hardness: "hard",
              reviewState: "automatic",
              sourceText: "Completed STAT2014",
              kind: "course",
              code: "STAT2014",
              minimumMark: null,
              requirementMode: "completed",
            },
            {
              confidence: 0,
              hardness: "hard",
              reviewState: "automatic",
              sourceText: "Completed STAT3008",
              kind: "course",
              code: "STAT3008",
              minimumMark: null,
              requirementMode: "completed",
            },
          ],
        },
        {
          kind: "group",
          operator: "any_of",
          minimumCount: null,
          conditions: [
            {
              confidence: 0,
              hardness: "hard",
              reviewState: "automatic",
              sourceText: "Completed MATH1113",
              kind: "course",
              code: "MATH1113",
              minimumMark: null,
              requirementMode: "completed",
            },
            {
              confidence: 0,
              hardness: "hard",
              reviewState: "automatic",
              sourceText: "Completed MATH1014",
              kind: "course",
              code: "MATH1014",
              minimumMark: null,
              requirementMode: "completed",
            },
            {
              confidence: 0,
              hardness: "hard",
              reviewState: "automatic",
              sourceText: "Completed MATH1116",
              kind: "course",
              code: "MATH1116",
              minimumMark: null,
              requirementMode: "completed",
            },
          ],
        },
      ],
    },
    hasPrerequisiteWording: true,
    availableCourseCodes: [
      "MATH1014",
      "MATH1113",
      "MATH1116",
      "STAT2001",
      "STAT2008",
      "STAT2013",
    ],
  },
];
